export const mockUser = {
  id: "uuid-12345",
  username: "wilfrid-k",
  email: "w@example.com",
  role: "admin" as const, // Change to "analyst" to preview that experience
  avatar_url: "https://github.com/wilfrid-k.png",
  created_at: "2023-01-15T10:30:00Z",
};

export const mockProfiles = [
  {
    id: "prof-001",
    name: "Harriet Tubman",
    gender: "Female",
    gender_probability: 0.98,
    age: 34,
    age_group: "Adult",
    country_id: "US",
    country_name: "United States",
    country_probability: 0.95,
    created_at: "2024-01-10T08:20:00Z",
  },
  {
    id: "prof-002",
    name: "Kwame Asante",
    gender: "Male",
    gender_probability: 0.96,
    age: 28,
    age_group: "Adult",
    country_id: "NG",
    country_name: "Nigeria",
    country_probability: 0.92,
    created_at: "2024-01-09T14:45:00Z",
  },
  {
    id: "prof-003",
    name: "Sofia Rodriguez",
    gender: "Female",
    gender_probability: 0.99,
    age: 42,
    age_group: "Adult",
    country_id: "MX",
    country_name: "Mexico",
    country_probability: 0.88,
    created_at: "2024-01-08T11:15:00Z",
  },
  {
    id: "prof-004",
    name: "James Chen",
    gender: "Male",
    gender_probability: 0.97,
    age: 19,
    age_group: "Teenager",
    country_id: "CN",
    country_name: "China",
    country_probability: 0.91,
    created_at: "2024-01-07T09:30:00Z",
  },
  {
    id: "prof-005",
    name: "Amara Okafor",
    gender: "Female",
    gender_probability: 0.95,
    age: 67,
    age_group: "Senior",
    country_id: "NG",
    country_name: "Nigeria",
    country_probability: 0.93,
    created_at: "2024-01-06T16:00:00Z",
  },
  {
    id: "prof-006",
    name: "Liam O'Brien",
    gender: "Male",
    gender_probability: 0.98,
    age: 31,
    age_group: "Adult",
    country_id: "IE",
    country_name: "Ireland",
    country_probability: 0.89,
    created_at: "2024-01-05T13:20:00Z",
  },
  {
    id: "prof-007",
    name: "Priya Sharma",
    gender: "Female",
    gender_probability: 0.96,
    age: 25,
    age_group: "Adult",
    country_id: "IN",
    country_name: "India",
    country_probability: 0.94,
    created_at: "2024-01-04T10:45:00Z",
  },
  {
    id: "prof-008",
    name: "Ahmed Hassan",
    gender: "Male",
    gender_probability: 0.99,
    age: 15,
    age_group: "Teenager",
    country_id: "EG",
    country_name: "Egypt",
    country_probability: 0.9,
    created_at: "2024-01-03T15:10:00Z",
  },
  {
    id: "prof-009",
    name: "Luna Bergstrom",
    gender: "Female",
    gender_probability: 0.97,
    age: 8,
    age_group: "Child",
    country_id: "SE",
    country_name: "Sweden",
    country_probability: 0.92,
    created_at: "2024-01-02T12:00:00Z",
  },
  {
    id: "prof-010",
    name: "Marcus Thompson",
    gender: "Male",
    gender_probability: 0.96,
    age: 55,
    age_group: "Senior",
    country_id: "US",
    country_name: "United States",
    country_probability: 0.96,
    created_at: "2024-01-01T09:30:00Z",
  },
];

export const mockPagination = {
  page: 1,
  limit: 10,
  total: 2847,
  total_pages: 285,
  links: {
    self: "/api/profiles?page=1&limit=10",
    next: "/api/profiles?page=2&limit=10",
    prev: null,
  },
};

export const isAuthenticated = true; // Change to false to test /login redirect
